### ISSUE TITLE
Erlang/OTP 26 compatibility

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/rabbitmq-server#7845]
Umbrella issue for things related to OTP26 compatibility

https://erlang.org/download/OTP-26.0-rc2.README
https://www.erlang.org/doc/general_info/upcoming_incompatibilities.html

First batch of changes has been merged:
https://github.com/rabbitmq/rabbitmq-server/pull/7900

The most important change is ready and tested (without this, we can't accept a client connection):
https://github.com/rabbitmq/rabbitmq-server/pull/7927

## Dialyzer defaults to `-Wunknown`, which makes it fail with errors such as these:
```
Unknown functions:
  compile:file/2 (c.erl:385:10)
  compile:forms/2 (escript.erl:647:12)
  compile:noenv_forms/2 (erl_abstract_code.erl:10:9)
  compile:noenv_forms/2 (qlc_pt.erl:444:14)
  compile:output_generated/1 (c.erl:444:10)
  crypto:crypto_one_time/5 (beam_lib.erl:987:11)
  crypto:start/0 (beam_lib.erl:1023:10)
  crypto:strong_rand_bytes/1 (net_kernel.erl:2093:37)
```
We can add all the necessary apps in the right places or use `-Wno_unknown`, at least for now

- [x] fix it in `bazel`
- [ ] fix it in `erlang.mk`
- [x] fix credentials-obfuscation repo (OTP PR https://github.com/erlang/otp/pull/7103) or a workaround

## `term_to_binary` defaults to `{minor_version, 2}`
- [x] [remove tests that expect version 1 by default](https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit/test/term_to_binary_compat_prop_SUITE.erl)
- [x] think through potential incompatibilities (mixed version clusters? reading data written by a different version?)

## different order in `maps:` operations (eg. `maps:to_list` or `maps:keys`); the order was never guaranteed but now it's different :)
- [x] fix tests that fail because of this (eg. [a test in Ra])(https://github.com/rabbitmq/ra/commit/d5e43c210783d3f8a082b973dfcd9923365afa49)
- [x] search for places where we might rely on the order but we don't test for this explicitly

## `verify_peer` is set by default

- [x] fix https://github.com/rabbitmq/rabbitmq-server/blob/main/deps/rabbit_common/mk/rabbitmq-dist.mk (it fails to download `mix_task_archive_deps`)

## BACKPORTING

OTP26 compatibility fixes need to be backported to `v3.12.x`, `v3.11.x`.
`v3.10.x` is optional, let's see how it goes

**Comment by mkuratczyk** [comment]
Status: all tests now pass on OTP 26. However, there's at least one upgrade issue:
https://github.com/rabbitmq/rabbitmq-server/issues/8057

We also still haven't solved all Dialyzer problems and haven't gone through `maps` calls to check for implicit order expectations that would not come up in tests for some reason.

**Comment by michaelklishin** [comment]
#8057 was addressed.

**Comment by mkuratczyk** [comment]
Update: OTP26 is officially supported starting with 3.12.0. It should also work with the most recent versions of 3.11 (3.11.17+) since most of the changes were backported but users of OTP26 are advised to use 3.12.

The only outstanding problem we have is that the [Test Windows](https://github.com/rabbitmq/rabbitmq-server/actions/workflows/test-windows.yaml) github action still fails. Some recent changes to OTP should fix this issue once they are shipped. I will keep this issue open until then.

**Comment by mkuratczyk** [comment]
Since we upgraded to Elixir 1.15.2, the tests have been running and passing on Windows.
https://github.com/rabbitmq/rabbitmq-server/actions/workflows/test-windows.yaml
